### PR TITLE
Fix cppcheck errors

### PR DESCRIPTION
**Pull request by mpope9**
When running a static analyzer, the following lines come up as issues:
```
> cppcheck xorfilter.h 
Checking xorfilter.h ...
[xorfilter.h:280]: (error) Memory leak: counts
[xorfilter.h:281]: (error) Memory leak: buffer
```

### CODE REVIEW

**Comment by lemire** [comment]
I don't understand the change you are proposing?

**Comment by mpope9** [comment]
My explanation wasn't so great.  I ran the static analyzer [cppcheck](http://cppcheck.sourceforge.net/) on the header files and these two errors came up.  They aren't major issues at all, but since they were reported I fixed them in my branch easily enough.

**Comment by lemire** [comment]
But is it a memory leak? And what is the error you are fixing?

**Comment by mpope9** [comment]
I don't really know if it is a memory leak, its just what the tool reported.

**Comment by lemire** [comment]
I am going to merge this, but there is no memory leaks there.

**Pull request merged**
