### PR TITLE
eliminating Warnings

### PR DESCRIPTION
**Pull request by oschonrock**
turning on -Wconversion and -Wsign-conversion

putting these 2 options into Makefile (but not CMakeLists.txt) and producing a silent compile

see individual commits for details

There were some minor changes in functions parameter and return types, which could do with checking. 

All tests pass.

### CODE REVIEW

**Comment by oschonrock** [comment]
this resolves https://github.com/FastFilter/xor_singleheader/issues/62

**Comment by thomasmueller** [comment]
The changes make the code harder to read, unfortunately. I wonder if it would be possible to change the type of the variables in at least some of the places, so that less casting is needed?

**Comment by oschonrock** [comment]
Yes, I agree. 

The casts really (mostly) indicate where there are problems with the types. So I do think that having them there as a first step is good. They act as a flag: "Problem here". The casts are happening anyway, just in an "uncontrolled and invisible way".   (which is why it is considered best practice to turn these warnings on)

I have already changed some types (as per comments above), of function params and return results. More can be done for sure. But in some cases it touches the core structs I believe, so I did not want to just go ahead and change that. If you me to go ahead and make more wholesale changes I can easily do that. 

Specifically:

1. The single most common problem is with size_t vs uint32_t... For reasons I don't understand some things which I think are related to the number of keys and should therefore not be bounded by a 32bit unsigned int, IMO. They should all just be size_t, IMO.  Unless there is some deeper algorithmic reasons that I do not understand.   This also goes for all things related to `malloc`.  That change alone would get rid of more than half the casts. 

2. The 'U's are unobtrusive IMO, so they can stay.

3. If more unsigned int's were used some more could eliminated. In this kind of code, almost nothing should be signed? And using `int` creates a lot of casting problems. 

4. the "integer promotion casts"... that's just a "feature" of C unfortunately, but I think it is still important to be aware that these promotions are happening.  In some cases these will also reduce when we do the other things above.

**Comment by oschonrock** [comment]
Alternative: 

If you decide that you don't want to go on this journey to improve the code/types by enabling -Wconversion and -Wsign-conversion, then one alternative is to offer a "non-header-only" version. 

Right now, because the library is header only, if a downstream user wants to follow best practices and enable those warnings, then they will be hit with a wall of warnings from `xor_singleheader`. This makes it very difficult to keep on top the resulting warnings in their own code. 

If they can use a "separately compiled" version of the library with a minimal interface header file, then the compile options for the library shared objects can be independently controlled in CMakeLists.txt. 

My personal sense/opinion is that the trend of "header_only" is coming to an end, because the community is improving its processes of integrating external dependencies. cmake, conan, vcpkg, etc are having an impact. Personally if I see that a project offers a simple `add_sudirectory()` way of including it via cmake, I will be happier to use that than a "just include this single header", because it's never quite as easy as that.. compile times, warnings, paths... etc...

**Comment by lemire** [comment]
@oschonrock 

I'll merge this. 

I agree with @thomasmueller but that's an internal issue that can be improved later.

**Pull request merged**
